### ISSUE TITLE
ACC csv file is not readable 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/gwb#19]
[@vogtpet](https://github.com/vogtpet), The csv from GWB_ACC seems to be a transcription of the txt file but the format does not respect the .csv convention and make it impossible to read by excel or Pandas in Python : 

here is the example.tif output:

```
Accounting size classes result using: /home/prambaud/module_results/gwb_results/tmp/input/example_bin_map.tif (more info in: acc.txt)
# Objects, Area[pixels], % of all objects, % of total FGarea
                  2789,                  31190,       97.8596,        7.2790497
                    44,                  23643,       1.54386,        5.5177484
                    14,                  98972,      0.491228,        23.097855
                     2,                  59874,     0.0701754,        13.973255
                     0,                      0,       0.00000,        0.0000000
                     1,                 214811,     0.0350877,        50.132092
 
ID, Area[pixels]
                     1,                 214811
                   901,                  33508
                  1662,                  26366
```

Will it be changed in future version of the lib ?

**Comment by vogtpet** [comment]
the csv-files are plain text files with comma-separated entries. They look ok here when imported in MS-Excel or LibreOffice. On the other hand, the txt-file provides the same and more info. Could we not just use this one?
Then I would have to add a text-file for LM as well, which is very easy.
But probably people will start whining when they don't have a csv-file. OK, let me see if I can write this out in a csv-compliant way

**Comment by 12rambau** [comment]
I've modifyed the file to make it csv compliant 

```
# Objects, Area[pixels], % of all objects, % of total FGarea
2789, 31190, 97.8596, 7.2790497
44, 23643, 1.54386, 5.5177484
14, 98972, 0.491228, 23.097855
2, 59874, 0.0701754, 13.973255
0, 0, 0.00000, 0.0000000
1, 214811, 0.0350877, 50.132092
ID, Area[pixels],,
1, 214811,,
901, 33508,,
1662, 26366,,
```

Main ideas : 
- no header in the csv file 
- remove tabulation
- always have the same number of column in each line

In this very cas you are actually displaying 2 different tables.
2 solutions : 
1. use one file and keep the number of column consistent (what I did in the provided file)
2. split the information in 2 csv files

**Comment by vogtpet** [comment]
I tested the IDL-native csv output option but looking at it in plain ascii text, the result is the same just with the tabular spaces removed. I fully agree with the ideas you mention. Suggested solution: your first option (use one file) and drop that second part (starting with: ID, Area[pixels]) of that file. This info (ID, Area[pixels]) is in the extended txt-file anyway, for those interested in extended output... Meaning, with your fix, the cdv-output issue is solved?

**Comment by vogtpet** [comment]
Is it possible to apply the same fix for the LM csv-file to get the triangular shaped cell output
![Screenshot 2021-03-12 at 12 39 09](https://user-images.githubusercontent.com/68806384/110935738-1d68ac00-8330-11eb-9ef9-f13a74efa95b.png)
?

**Comment by 12rambau** [comment]
ahhhh now I understand the file shape (I'll respond on the other issue)
