### ISSUE TITLE
LM .csv file is not readable 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/gwb#20]
[@vogtpet](https://github.com/vogtpet), The csv from GWB_ACC seems to be a transcription of the txt file but the format does not respect the .csv convention and make it impossible to read by excel or Pandas in Python : 

here is the cl3class.tif output:

```
Landscape Mosaic using Window size (23x23)
, , , , , , , , , ,      10.533,
, , , , , , , , , ,      3.320,
, , , , , , , , ,     0.222,    0.049,      1.949,
, , , , , , , ,     0.182,    0.036,    0.037,    0.045,      1.867,
, , , , , , ,     0.171,    0.031,    0.029,    0.031,    0.038,    0.047,      1.985,
, , , , , ,     0.157,    0.029,    0.027,    0.028,    0.031,    0.034,    0.038,    0.049,      2.107,
, , , , ,     0.154,    0.027,    0.025,    0.026,    0.028,    0.029,    0.031,    0.032,    0.040,    0.062,      2.199,
, , , ,     0.155,    0.026,    0.028,    0.024,    0.028,    0.029,    0.029,    0.029,    0.037,    0.035,    0.048,    0.065,      2.322,
, , ,     0.161,    0.026,    0.028,    0.026,    0.027,    0.030,    0.033,    0.029,    0.035,    0.036,    0.042,    0.047,    0.057,    0.074,      2.542,
, ,     0.171,    0.029,    0.026,    0.026,    0.029,    0.030,    0.037,    0.036,    0.041,    0.039,    0.043,    0.045,    0.052,    0.053,    0.069,     0.102,      3.059,
,      1.632,    0.027,      1.129,    0.030,      1.202,    0.040,      1.341,    0.048,      1.541,    0.058,      1.786,    0.063,      2.136,    0.068,      2.594,    0.091,      3.112,     0.157,      10.548,
      5.296, , , , , , , , , , , , , , , , , , , ,      31.440,
```

It's easier to correct than for [ACC](https://github.com/12rambau/gwb/issues/19), here the number of element per line is not homogeneous (header mus have `,`as well) and a line should not finish by a `,`.

Will it be changed in future version of the lib ?

**Comment by vogtpet** [comment]
I will try to write this out in a csv-compliant way.

**Comment by 12rambau** [comment]
Now that I better understand what was the objective, here is a proposal to illustrate how a csv file should be writen : 

```
Landscape Mosaic using Window size (23x23),      ,      ,      ,      ,      ,      ,      ,      ,      ,       ,      ,      ,      ,      ,      ,      ,      ,      ,       , 
                                          ,      ,      ,      ,      ,      ,      ,      ,      ,      , 10.533,      ,      ,      ,      ,      ,      ,      ,      ,       ,
                                          ,      ,      ,      ,      ,      ,      ,      ,      ,      ,  3.320,      ,      ,      ,      ,      ,      ,      ,      ,       ,
                                          ,      ,      ,      ,      ,      ,      ,      ,      , 0.222,  0.049, 1.949,      ,      ,      ,      ,      ,      ,      ,       ,
                                          ,      ,      ,      ,      ,      ,      ,      , 0.182, 0.036,  0.037, 0.045, 1.867,      ,      ,      ,      ,      ,      ,       ,
                                          ,      ,      ,      ,      ,      ,      , 0.171, 0.031, 0.029,  0.031, 0.038, 0.047, 1.985,      ,      ,      ,      ,      ,       ,
                                          ,      ,      ,      ,      ,      , 0.157, 0.029, 0.027, 0.028,  0.031, 0.034, 0.038, 0.049, 2.107,      ,      ,      ,      ,       ,
                                          ,      ,      ,      ,      , 0.154, 0.027, 0.025, 0.026, 0.028,  0.029, 0.031, 0.032, 0.040, 0.062, 2.199,      ,      ,      ,       ,
                                          ,      ,      ,      , 0.155, 0.026, 0.028, 0.024, 0.028, 0.029,  0.029, 0.029, 0.037, 0.035, 0.048, 0.065, 2.322,      ,      ,       ,
                                          ,      ,      , 0.161, 0.026, 0.028, 0.026, 0.027, 0.030, 0.033,  0.029, 0.035, 0.036, 0.042, 0.047, 0.057, 0.074, 2.542,      ,       ,
                                          ,      , 0.171, 0.029, 0.026, 0.026, 0.029, 0.030, 0.037, 0.036,  0.041, 0.039, 0.043, 0.045, 0.052, 0.053, 0.069, 0.102, 3.059,       ,
                                          , 1.632, 0.027, 1.129, 0.030, 1.202, 0.040, 1.341, 0.048, 1.541,  0.058, 1.786, 0.063, 2.136, 0.068, 2.594, 0.091, 3.112, 0.157, 10.548,
5.296                                     ,      ,      ,      ,      ,      ,      ,      ,      ,      ,       ,      ,      ,      ,      ,      ,      ,      ,      ,       , 31.440

```

All the blanck space between `,`can be removed, it was just to illustrate that the `,`are the cell border of the excel table. 
For consistency, the number of cell must be the same on each line even the header.

**Comment by vogtpet** [comment]
ok, I changed the cell output to be the same on each line and shifted to have the title in the first column, like this:
[clc3class_lm_23_heatmap.txt](https://github.com/12rambau/gwb/files/6130823/clc3class_lm_23_heatmap.txt)
(rename the txt extension to csv and then open it, appears correct here)
Please let me know if this output format is ok then I will have to check any other module-specific csv-output .

**Comment by 12rambau** [comment]
It works perfectly. 
Just keep in mind that this file is adding 1 extra cell at the end as you finish all the lines by a `,` (but as long as people know it it perfectly usable

**Comment by vogtpet** [comment]
is this one extra cell at the end a problem? I thought to put it there for 'cosmetic reason', so that triangular shape does not 'hit the wall' at the right side of the table.
I will check all other modules for csv-output and then get back to you.

**Comment by 12rambau** [comment]
normally I checked all the other modules result and they were the 2 only defaulting one.

I would say that the file will be digested anyway, so there is no cosmetic consideration when writing a .csv

**Comment by vogtpet** [comment]
ok, I will take it off then from the LM. Also change the ACC output to no longer list that second part. Will send you all new csv output tests on Monday, and once all is ok, then package it up into a new release.

**Comment by vogtpet** [comment]
faster than I thought. I think this only concerned ACC and LM, all others look ok as they are. Attached is the new modified ACC and LM, just rename the extension to csv and let me know if they are ok please. Thanks!
[example_acc.txt](https://github.com/12rambau/gwb/files/6131703/example_acc.txt)
[example_lm_23_heatmap.txt](https://github.com/12rambau/gwb/files/6131704/example_lm_23_heatmap.txt)

**Comment by 12rambau** [comment]
> faster than I thought. I think this only concerned ACC and LM, all others look ok as they are. Attached is the new modified ACC and LM, just rename the extension to csv and let me know if they are ok please. Thanks!
> [example_acc.txt](https://github.com/12rambau/gwb/files/6131703/example_acc.txt)
> [example_lm_23_heatmap.txt](https://github.com/12rambau/gwb/files/6131704/example_lm_23_heatmap.txt)

There are both perfectly readable, nice addition to the ACC one

**Comment by vogtpet** [comment]
I think this issue can be closed as well?

**Comment by 12rambau** [comment]
I hadn't the time to test them both yesterday but yes it's now perfectly readable as well
