### ISSUE TITLE
small typos

### ISSUE THREAD

**Issue by vogtpet** [12rambau/gwb#21]
There are small typos, corrected versions below:

About:
GWB is a subset of the desktop software package GuidosToolbox (GTB) designed as a modular application for the SEPAL platform.

Contribute:
...If you used Jupyter notebook, click on the ...

**Comment by 12rambau** [comment]
You can also modify the Readme the exact same way as you did for the documentation. Go to the [readme.md](https://github.com/12rambau/gwb/blob/master/README.md) file and click on the "edit" btn.
