### ISSUE TITLE
Bad link redirection

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/gwb#23]
When one of the module external links is clicked, the url is tried to be loaded from inside sepal instead in a new tab, which is retrieving an error.
![image](https://user-images.githubusercontent.com/12363250/112376165-6af7f800-8ce4-11eb-8586-3519c2847f76.png)

**Comment by 12rambau** [comment]
super strange. I cannot reproduce this behavior on my side. 

- If I hover the link, it's the right one. 
- If I only click, nothing happen.
- if I do `cmd + click` (open in a new tab mac shortcut) It opens itself nicely. 

could you just confirm that "open in a new tab" works ? 

if yes, I'll add the `{target:_blanck}` in the links (hoping that is interpreted by Python markdown)

**Comment by ingdanielguerrero** [comment]
Yes, I can confirm that the link will be opnened if you add teh _blank attribute, I tested with ctr+click, and the "open in a new tab" right-click option.

**Comment by 12rambau** [comment]
solved with sepal_ui 2.4
