### ISSUE TITLE
module description text amendments

### ISSUE THREAD

**Issue by vogtpet** [12rambau/gwb#29]
Below are some suggestions for text changes in the modules:
All modules:
- [x] menu title “Select map classes”: maybe better “Select input map classes”
- [x] button "Download Test Dataset”: add the following text line below this button: Click the button above to download the test files “clc3class.tif" and “example.tif” into the folder “downloads” 
- [x] button "CONVERT THE IMAGE CLASSES": maybe better "CONVERT THE INPUT IMAGE CLASSES"

Specific modules:
ACC:
- [x] Provide a byte-formatted input image. Recode the classes into the following 4 classes: background (nonforest), foreground (forest), special background 1 (optional, e.g. water) and special background 2 (optional). All remaining classes will be considered as missing data.
- [x] Dropdown menu text: special background 1 (optional)
- [x] Dropdown menu text: special background 2 (optional)
- [x] Dropdown menu text: output options: stats + image of viewport (default)

DIST:
- [x] Provide a byte-formatted input image. Recode the classes into the following 2 classes: background (nonforest), foreground (forest). All remaining classes will be considered as missing data.
- [x] Dropdown menu text: Euclidean distance only (default)

FAD/FRAG:
- [x] Provide a byte-formatted input image. Recode the classes into the following 4 classes: background (nonforest), foreground (forest), special background 1 (optional, e.g. water) and special background 2 (optional). All remaining classes will be considered as missing data.
- [x] Dropdown menu text: special background 1 (optional)
- [x] Dropdown menu text: special background 2 (optional)

LM:
- [x] Provide a byte-formatted input image. Recode the classes into 3 dominant land cover classes. All remaining classes will be considered as missing data.
- [x] Dropdown menu text: Dominant land cover 3 (Developed)

MSPA:
- [x] Provide a byte-formatted input image. Recode the classes into the following 2 classes: background (nonforest), foreground (forest). All remaining classes will be considered as missing data.
- [x] The last slider text should read: intext (instead of the current: int ext)

P223:
- [x] Provide a byte-formatted input image. Recode the classes into the 3 following classes: background (nonforest), foreground (forest), special background (for P23 only). All remaining classes will be considered as missing data.
- [x] Dropdown menu title: Computation precision
- [x] Dropdown menu entry: float precision (default, but requires more disk space)

PARC:
- [x] Provide a byte-formatted input image. The input image must contain at least 2 different classes. The class value 0 will be considered as missing data.

RSS:
- [x] Provide a byte-formatted input image. Recode the classes into the following 2 classes: background (nonforest), foreground (forest). All remaining classes will be considered as missing data.

SPA:
- [x] Provide a byte-formatted input image. Recode the classes into the following 2 classes : background (nonforest), foreground (forest). All remaining classes will be considered as missing data.
- [x] Dropdown menu: Number of pattern classes: prepend the number of classes before the description like this
2: Small & linear features (SLF), Coherent
3: Core, Core-Openings, Margin
5: Core, Core-Openings, Edge, Perforation, Margin
6: Core, Core-Openings, Edge, Perforation, Islet, Margin

**Comment by 12rambau** [comment]
instead of a hint I've added a tooltip to the test download btn

**Comment by vogtpet** [comment]
I still think it would be better to write that sentence below, or maybe even better above, the Download button. The tooltip thing I since but not used anywhere else. Writing the text above  the button is more obvious because you can always read it and it reminds the user where the files have been downloaded to, without having to hover over the button.

**Comment by vogtpet** [comment]
what changed here: only the word _below_ replaced by _above_ in the tooltip? The idea was to not use any tooltips anywhere because tooltips are not evident, they are hidden unless you know where to place the mouse. imo, it would be much better to write the following sentence below the DOWNLOAD TEST DATA button:
Click the button above to download the test images "example.tif" and "clc3class.tif" into the folder "downloads" in your user account.

**Comment by 12rambau** [comment]
No in convert_tile.py I removed the ttoltip and used a Markdown object instead. So now there are no tooltip bu just text display above the btn.
