### ISSUE TITLE
downloads folder not showing

### ISSUE THREAD

**Issue by vogtpet** [12rambau/gwb#32]
In the GWB-APP module interface and after having clicked on the button: DOWNLOAD TEST DATASET: the two images are downloaded correctly in ~/downloads/. But in the next step, when clicking on the button SEARCH FILE, the directory "downloads" is not listed (also after clicking the reload button), so the example input images can not be selected this way.
![Screenshot 2021-04-13 at 11 31 15](https://user-images.githubusercontent.com/68806384/114531333-180ec200-9c4c-11eb-8e8e-dbc2778fc6c4.png)

**Comment by 12rambau** [comment]
I was thinking the downloads folder was a default folder as tmp
Maybe I was wrong and I should create it at start 

If you go to the file manager, you have no trace of a downloads folder ? 

> If it exists, try to click on the refresh btn next to the TextField it will refresh the folder list

**Comment by vogtpet** [comment]
I have/had no "downloads" folder in my $HOME. Some Linux distros have a "Download" folder by default defined in /etc/skel but SEPAL has nothing defined in /etc/skel. Two situations: 
a) the user already has a folder $HOME/downloads: if you click on the DOWNLOAD TEST DATASET button, the action will work as expected
b) the user does not have a folder $HOME/downloads: if you click on the DOWNLOAD TEST DATASET button, then this action will create a _file_ named "downloads" but not a folder...

The fix would be that clicking on the DOWNLOAD TEST DATASET button should always execute: `mkdir -p $HOME/downloads; cp -f /opt/GWB/input/*.tif $HOME/downloads/`
