### ISSUE TITLE
DOWNLOAD TEST DATASET creates a file instead of a folder

### ISSUE THREAD

**Issue by vogtpet** [12rambau/gwb#35]
a native $HOME does not have a folder named: downloads
When clicking on the DOWNLOAD TEST DATASET button, this action will create a file named "downloads" but not a folder...

The fix would be that clicking on the DOWNLOAD TEST DATASET button should always execute the following command: 
`mkdir -p $HOME/downloads; cp -f /opt/GWB/input/*.tif $HOME/downloads/`

**Comment by 12rambau** [comment]
I think I solved it here: https://github.com/12rambau/gwb/commit/33e5d1e372282d7b85c60e42938752cdc6c0f088

I've updated the release branch, it should work in 5 min

**Comment by vogtpet** [comment]
launching the GWB-APP will now automatically create the folder ~/downloads
and clicking on the DOWNLOAD TEST DATASET button will download the two images. Issue solved, thanks!
