### ISSUE TITLE
Images don't show up

### ISSUE THREAD

**Issue by vogtpet** [12rambau/gwb#39]
2 issues on the [cli-doc page](https://docs.sepal.io/en/latest/modules/dwn/gwb.html):

1) the example result images **at the end of each module description** don't show up:
![Screenshot 2021-04-15 at 09 37 44](https://user-images.githubusercontent.com/68806384/114832276-9a26f400-9dce-11eb-989f-e54289ebc5d9.png)

2) Could we update this older image:
![Screenshot 2021-04-15 at 09 37 25](https://user-images.githubusercontent.com/68806384/114834077-83819c80-9dd0-11eb-8287-fe6aa63753b4.png)

with the new version:
![Screenshot 2021-04-15 at 09 42 44](https://user-images.githubusercontent.com/68806384/114832652-030e6c00-9dcf-11eb-94a5-fa067f8dc141.png)

The same on the [GWB-APP doc-page](https://docs.sepal.io/en/latest/modules/dwn/gwb.html):
1) the example result images **at the end of each module description** don't show up, for example:
![Screenshot 2021-04-15 at 18 21 45](https://user-images.githubusercontent.com/68806384/114903813-763bd080-9e17-11eb-9f09-76389920c1fa.png)

2) Could we update this older image:
![Screenshot 2021-04-15 at 09 37 25](https://user-images.githubusercontent.com/68806384/114834077-83819c80-9dd0-11eb-8287-fe6aa63753b4.png)

with the new version:
![Screenshot 2021-04-15 at 09 42 44](https://user-images.githubusercontent.com/68806384/114832652-030e6c00-9dcf-11eb-94a5-fa067f8dc141.png)

**Comment by 12rambau** [comment]
I think that the image were reloading in github OR the JRC proxy was blocking it. It work lika charm on my side:

![Capture d’écran 2021-04-16 à 15 53 07](https://user-images.githubusercontent.com/12596392/115034489-da1fd100-9ecb-11eb-9a17-dfc81fb0c04f.png)

I'm changing the picture for the download_test_dataset
