### ISSUE TITLE
adapt to latest release

### ISSUE THREAD

**Issue by 12rambau** [12rambau/gwb#42]
copied from @vogtpet email: 

## GWB_ACC: 
Accounting now has a new option (big3pink) to not show the 3 largest patches in pink color (because some people find this disturbing) and I will update the documentation here and here accordingly. The new option implies that the file: input/acc-parameters.txt is now one line longer and hence reading the parameters is now shifted by one line plus reading the new parameter big3pink.
 
## GWB_FRAG:
The fragmentation analysis has a new option to do a 5-class analysis, which in fact is doing the 6-class analysis but merging the top two classes (intact and interior) into one class Interior. The rational here is that the class “Intact” (FAD=100%) is very restrictive and potentially conflicting with the thematic topic “intact forests”. People insisting on showing areas where FAD=100% can still use the option FOS6, while the new option FOS5 is now the default. The line numbers to read in the input/frag-parameters.txt are the same as before so there are no changes needed on SEPAL but I will update the documentation accordingly.
 
## GWB_check4updates
Is a new function which shows version info and, you guessed it, will check for program updates. Nothing to be implemented on SEPAL but maybe I can add a note in the documentation.

## TODO list
- [x] GWB_ACC
- [x] GWB_FRAG

**Comment by 12rambau** [comment]
@vogtpet the FRAG has actually changed, In the previous implementation parameters where the same as the FAD one and now they are called FOS, I changed the files accordingly

**Comment by vogtpet** [comment]
sorry for the oversight and thank you for fixing this!
