### ISSUE TITLE
remove the obsolete mspa in sepal 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/gwb#6]
the MSPA implementation provided in this module is far more advanced than the previous one, MSPA analysis (R and Python) needs to be removed from the plateform
same for the mspa implementation in the gfc tool

**Comment by vogtpet** [comment]
Ok, maybe mention that the (feature-limited) MSPA-implementation can be downloaded from the [MSPA-homepage](https://forest.jrc.ec.europa.eu/en/activities/lpa/mspa/#Download): GIS-plugin with documentation and installation info for ArcGIS, QGIS3 and R.

**Comment by 12rambau** [comment]
@vogtpet Mentioning it in the "about" section of the module ?

**Comment by vogtpet** [comment]
yes, good idea!

**Comment by 12rambau** [comment]
done here : https://github.com/openforis/sepal/issues/83
